#!/bin/sh
set -euo pipefail

# Sanity check things seem sensible
if [ ! -d ".git" ]; then
    echo "we don't seem to be in the root of the repo..." >&2
    exit 1
fi

set +e
output=$(go build ./... 2>&1)
status=$?
set -e
if [ $status -ne 0 ]; then
    echo "pre-commit: go build exited with $status" >&2
    echo "$output" >&2
    exit $status
fi

set +e
output=$(go test -v ./... 2>&1)
status=$?
set -e
if [ $status -ne 0 ]; then
    echo "pre-commit: go test exited with $status" >&2
    echo "$output" >&2
    exit $status
fi
